name: Build wheel
permissions:
  contents: write

defaults:
  run:
    shell: bash

on:
  push:
  pull_request:
  schedule:
    - cron: '37 22 * * *'
  workflow_dispatch:

jobs:
  gha:
    runs-on: windows-2019
    strategy:
      fail-fast: false
        
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: git clone
      run: |
        git clone https://github.com/lxml/lxml.git
        cd lxml
        git tag --list
        export latest_release=$(git tag --list | grep lxml- | sort -Vr | head -n1)
        echo "Checking out tag ${latest_release}..."
        git checkout "${latest_release}"

    - name: Build lxml wheel
      uses: pypa/cibuildwheel@v2.23.2
      with:
        only: cp313-win_arm64
        package-dir: lxml

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        automatic_release_tag: "latest"
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        draft: false
        title: "Wheel Build"
        files: |
          wheelhouse/*.whl

  testwheel:
    needs: gha
    runs-on: windows-11-arm
    steps:

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          check-latest: true

      - name: download and install wheel release
        run: |
          latest_lxml_whl=$(curl https://api.github.com/repos/GAM-team/lxml-wheel/releases/latest -s | jq -r .assets.[0].browser_download_url)
          echo "Downloading ${latest_lxml_whl}..."
          curl -O -L "$latest_lxml_whl"
          python3 -m pip install lxml*.whl

      - name: Run XML
        run: |
          python3 -c "from lxml import etree; root = etree.Element('root'); print(etree.tostring(root, pretty_print=True));"
          
